branch-defaults:
  master:
    environment: Jiayanudagramapi2-env
environment-defaults:
  Jiayanudagramapi2-env:
    branch: null
    repository: origin
global:
  application_name: Jiayanudagramapi2
  default_ec2_keyname: null
  default_platform: Node.js 12 running on 64bit Amazon Linux 2/5.4.9
  default_region: us-east-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  sc: git
  workspace_type: Application
deploy:
  artifact: www/Archive.zip
