# This config uses the `.circleci/extended/orb-test.yml` as its base, and then publishes the app to S3.
# The workflow contained here demonstrates a practical application of `post-steps`
# and using workspace persistence
version: 2.1
orbs:
  node: circleci/node@4.1.0
  aws-cli: circleci/aws-cli@1.3.1
jobs:
  build:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install
      - checkout
      - aws-cli/setup
      - run:
          name: Install dependencies
          command: |
            sudo apt update
            sudo apt install python3-pip python-dev
            sudo pip install awsebcli
      - run:
          name: Front-End Install
          command: |
            npm run frontend:install
      - run:
          name: Back-End Install
          command: |
            npm run backend:install
      - run:
          name: Front-End test cases
          command: |
            echo "skip front-end test."  # npm run backend:test
      - run:
          name: Back-End test cases
          command: |
            echo "skip backend test."  # npm run backend:test
      - run:
          name: Front-End Build
          command: |
            npm run frontend:build
      - run:
          name: Back-End Build
          command: |
            npm run backend:build
      - run:
          name: Front-End Test
          command: |
            npm run frontend:test
      - run:
          name: Back-End Test
          command: |
            npm run backend:test
      - run:
          name: Deploy Front-End
          command: |
            echo "deploying frontend"
            aws s3 sync ./udagram-frontend/www s3://udagramfrontendjyx
      - run:
          name: Deploy Backend
          command: |
            echo "Deploying api to ebs."
            cd ./udagram-api
            eb deploy Jiayanudagramapi2-env
            eb setenv -e Jiayanudagramapi2-env AWS_ACCESS_KEY=$AWS_ACCESS_KEY AWS_BUCKET=$AWS_BUCKET AWS_PROFILE=$AWS_PROFILE AWS_REGION=$AWS_REGION AWS_SECRET=$AWS_SECRET JWT_SECRET=$JWT_SECRET PORT=$PORT POSTGRES_DB=$POSTGRES_DB POSTGRES_HOST=$POSTGRES_HOST POSTGRES_PASSWORD=$POSTGRES_PASSWORD POSTGRES_PORT=$POSTGRES_PORT POSTGRES_USERNAME=$POSTGRES_USERNAME URL=$URL
            
            
